---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres16
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4-3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 10GB
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 7d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: https://vdhbackupstorage.blob.core.windows.net/cnpg/
      serverName: &currentCluster postgres-v23 # change/increment when restoring as value cannot match existing cnpg cluster
      azureCredentials:
        connectionString:
          name: cloudnative-pg-secret
          key: azure-connection-string
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  #   - name: *previous-cluster
  #     barmanObjectStore:
  #       wal:
  #         compression: bzip2
  #         maxParallel: 8
  #       destinationPath: https://vdhbackupstorage.blob.core.windows.net/cnpg/
  #       azureCredentials:
  #         connectionString:
  #           name: cloudnative-pg-secret
  #           key: azure-connection-string
