---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: powerwalker-ups-devices
spec:
  rules:
    - name: "powerwalker.ups"
      labels:
        "feature.node.kubernetes.io/ups": "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: {op: In, value: ["06da"]}

