---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: home-automation
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: mealie-secret

        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.0.2@sha256:448d56c5b41b668a8e2f0e435ade52ce6bd574d906d3e45eba1e9a1d05f844ff
            env:
              TZ: "Europe/Amsterdam"
              BASE_URL: https://mealie.${SECRET_DOMAIN}
              DB_ENGINE: postgres
              SMTP_HOST: mail.smtp2go.com:2525
              SMTP_PORT: 587
              SMTP_FROM_NAME: Mealie
              SMTP_FROM_EMAIL: noreply@${SECRET_DOMAIN}
              SMTP_AUTH_STRATEGY: TLS
              OPENAI_BASE_URL: https://openrouter.ai/api/v1
            envFrom: *envFrom
            resources:
              requests:
                memory: 250Mi
                cpu: 50m
              limits:
                memory: 500Mi

    service:
      app:
        controller: mealie
        ports:
          http:
            port: 9000

    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: "mealie.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        enabled: true
        existingClaim: mealie-pvc
        globalMounts:
          - path: /app/data
