---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: mealie

  values:
    controllers:
      *app:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: mealie-secret

        containers:
          *app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.3.2@sha256:d51ae3b5051439844c1bbe437fb7edffa0826cb9988b366e17ffc7170a8d5ed2
            env:
              TZ: "Europe/Amsterdam"
              BASE_URL: https://mealie.${SECRET_DOMAIN}
              DB_ENGINE: postgres
              SMTP_HOST: mail.smtp2go.com:2525
              SMTP_PORT: 587
              SMTP_FROM_NAME: Mealie
              SMTP_FROM_EMAIL: noreply@${SECRET_DOMAIN}
              SMTP_AUTH_STRATEGY: TLS
              DAILY_SCHEDULE_TIME: 01:45
              OPENAI_BASE_URL: https://openrouter.ai/api/v1
              OPENAI_MODEL: openai/gpt-5-mini
            envFrom: *envFrom
            resources:
              requests:
                memory: 250Mi
                cpu: 50m
              limits:
                memory: 500Mi

    service:
      *app:
        controller: mealie
        ports:
          http:
            port: 9000

    ingress:
      *app:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: "mealie.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: *app
                  port: http

    persistence:
      data:
        enabled: true
        existingClaim: mealie-pvc
        globalMounts:
          - path: /app/data
