---
# yaml-language-server: $schema=https://github.com/bjw-s/helm-charts/blob/6d23aa66ca7a707249b7f4c2ca28bf46e4ab1357/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-red
spec:
  releaseName: node-red
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: home-assistant
      namespace: home-automation
  values:
    controllers:
      main:
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            image:
              repository: docker.io/nodered/node-red
              tag: 4.0.9@sha256:7a3e18f29578feb271bb8daab4379e4ebd355b87ea64b699ce74e6ff49d907aa
            env:
              TZ: "Europe/Amsterdam"
              NODE_RED_ENABLE_PROJECTS: "true"
              NODE_RED_ENABLE_SAFE_MODE: "false"
            resources:
              requests:
                memory: 350Mi
                cpu: 25m
              limits:
                memory: 500Mi
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 1880
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths: &paths
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        size: 5Gi
        accessMode: ReadWriteOnce
        advancedMounts:
          main:
            main:
              - path: /data
