---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1eg2mmjn7jwd2qqs4nppsz3pehxrkatw4npx3php5eqxwcdc92a3qkpd3t6"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1eg2mmjn7jwd2qqs4nppsz3pehxrkatw4npx3php5eqxwcdc92a3qkpd3t6"
