---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minio-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: minio
