---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: music-assistant-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  volumeName: music-assistant-data-pv
  storageClassName: music-assistant-data-storage-class

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-assistant-data-pv
  labels:
    type: longhorn
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: music-assistant-data-storage-class
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: music-assistant-data-ext4
