---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev//kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname influxdb
  namespace: flux-system
spec:
  targetNamespace: database
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: "./kubernetes/apps/database/influxdb/app"
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: longhorn
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *appname
  prune: true
  wait: true
  interval: 60m
  retryInterval: 1m
  timeout: 5m
