apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:skkRNY+oupk0DhZWmg1M9H8X922A7q+Ndow5IgdAGmHAXAd6,iv:DrnmMIPAa18lrRyfT4IrTgcSti9QAD6lhBRGseZpFuM=,tag:vcb/0i43/rEV/GHsDvwyXQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:AfmdO6HsjcR2pOsv87X68NRvlvmEHyd9k09vsSBM69EkRPX82t0X1MYImvNFjWEuv/oTpZujVMskIYNNz0Y6Ybyu/0y3HLqoDuuKFUTwEnZH8W1v4J1qvDCb3Aneb/0ducwWcYUWAqaOuBfwBYjUF7I2pe3N+qweSJQZFNKeyWeZ9iFeblqy5nrzgoAGOEdROPchxZQfttido2HhE3LhukZMxUb7nFKwIev1Tc5eJA==,iv:wvEO1rsx+cAB42GKThfjkdD/MnN0LE5vAhXppt7t0y4=,tag:E2zdtcIY7ZvQ0AMDMGcHyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwpkc7nndlsql07awyjlgynhlmwnt0hjwncppqa7ctf83acwwpzsuxt97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YWlJa2JnVWtkam0zL2J1
            MVdFcVh6VXZBSXJjMkhTRkFWdXRaejI3T0hRCnkzZkhiWlEyd3M5TkRPWk9qZDZi
            eDFpaUpUOWxJVnBTeklWdlJDTWRFVjQKLS0tIHlrNkdnRkZTdDdMZHhaMWZOZEZR
            ZGVZZG01UE0wRGRrcS9hMGxiOFJlNWsKirDzV5QMUKA9HwW0i69MCHf/GGG7GnA3
            vrDoCskm958/5k0LPLiS/4Npk3+tXoRyVdx6Ntpyy0PdlmnPHnWQbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:16:10Z"
    mac: ENC[AES256_GCM,data:HoJoHD+u5HO2ovtSMhBmxDYqCUA+uiOzcm48cRDG4E1UHGeZnIU9aj6Do5yMGamSkiceLbWpFbdjtSDj18SuwjtxVlqxln967BgaoYKCg3WabVSE6zwkujHJa5d9dPfuwdCaT3fxL6Eyg+S4UaL2AB3PMhjlTnn5X4ak/wgZlAk=,iv:IbPTR7NTtk1coofSWrCi3/BakR0tfnCn/RRDxzl/Uuo=,tag:uGWkr9ZkCsN6kjl+oEW6Rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
