apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:8h3ONgR5G6hzrq6Ah0F3JmMEySpNaMaOkx1snqiTbWkrfowV,iv:728cQfn9l5IxEeY/OpGnuWlm/oNtLTfCttbk0J8qgq8=,tag:EYb/kEzdu4G0/a9S0UaRYg==,type:str]
    credentials.json: ENC[AES256_GCM,data:tUB451ygcGuA47qJkkXdH3Sjy+0hzbOJCNYQxdlwVwCMV+CQY9XdCmWs21sb1lg5qiathKFYROqsEaoAB1VnHGrRbgbDm+yEfO44J1stXOvjYiTrDyl4xVy5M4KeMnAfVy1gbWG3/zV9EM7mc5IG9/b/1FMaUzvqUoyMbl5Y+fBu2ePWe1Eayjuk/DMcD4znsco44gRLifIcHlPraYOXXKygwmQDpA78exWjqNpMaQ==,iv:Sb6+Rd9VStrn+K0KqtGPrRQQ6JLf6nWfCN08FmePD8g=,tag:S8Yrh06+PeZH0DvTqwCMYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dfs2z6esr6rhm46pvh6l8xlualxsn756rkkt9432d5kk3k7s4pssmus4gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZU1xYXYvU0ZnMjNyMjRZ
            U1hjNFNmMmFqd0dKa2pYYyszZ0hHWjFGa3g4CkhxdHJKWkpkeEhJRzdaVjh1NWRP
            VHRSTmhJd3l5VVRFcjVrWDVKdHk0cDgKLS0tIGFWNUZSSDZOdktrOHorUEt1TXJD
            VzhaUFI1eGJLNC83WHREaFpIcVo3UVUK8RyHMaJUFYVPPn6F3Wuov8dbetKrEDaU
            vMbNpIlng4nb191fLzrINDnVZuLZTKvvINYJHG/4c2LAturwt98UYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T20:40:36Z"
    mac: ENC[AES256_GCM,data:yT+vZvyoUJ+evQpkQl6NoLS4h4MdLpDQ8boRyjFKh0tUnBuNAKcDdRXIUdiP+FIdLH+8LzA6XGYJmdepiOmzk7KsiTxG2XbGzN/Avd6LuZVAQnPEPV6pKrC8yUJkj8GFhUauHp1v5RntC5o7IzhFjUeK/4KhbYtiwsFwnaUgg5g=,iv:USXBW3PnT26h31+fZUayyNETr7eY6A0GfGvSPgTIYlY=,tag:iw4E8PcGMtnBocRboCwuIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
