apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:wyYnvpzC96faoaV/eA68ALXbTXNyL4kqiaftWsF0StIWb0cP,iv:wDtkL5F5H5v87RMr96Wu/g1qBC5qEVFOZ6+ceXsQcE4=,tag:hxSDIh9jXM7rHge328LEhg==,type:str]
    credentials.json: ENC[AES256_GCM,data:xPr4SpVAC/3cO8cCoMTw80QClnyYdMoVV1sT31cFi/AbzOSfiphyMhu2rMURx0mI7+ydwd5R4QFRVDgwc8VLtcy7BhViVbmPbTajNTlLHf13AbxnE5RffjK5po1Y41w3tPmQi7HfYRQ0oVsbAFSFL4MMxvpSCXms2mruLt8pxBzML0euRwa3uJBkzzWkvoL90END26szJiviaVgAPc6+Axy2EYiSep6/9Op/xezEpg==,iv:TTxaYVKxUleGssGs0iTXa4eZosj+YVq1Y2Y3hRaiEx0=,tag:/a1kr3rVG9ZEj9c96vPeWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eg2mmjn7jwd2qqs4nppsz3pehxrkatw4npx3php5eqxwcdc92a3qkpd3t6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzRUVBL1pUWjJIZFo5d0xh
            Q0Z2QUhNbnJuc01xMUhUR1JOKysxVGd2emtvCk9hdUZ4ZFBVdjRkOUpaZDdvRzZx
            SmRlNEtjWnAzNmpSZWpWWUJEblJpRWMKLS0tIFZlNXBUZ0ViOFZhOHpzY2xtSjdN
            M0JIdm4rNE85ZnV2NTltVGZ4N2U0NVkKbK9fvf+na3p61spkq3Flk3BjFOWIkXjd
            kuHvl78+sXHptrC/1k1CDoRBfd5TCwvTjkXkrAXhPY2pEy8s7ba8xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T12:09:24Z"
    mac: ENC[AES256_GCM,data:brXw32bSsWEFsMjs3tEBh9+yNvyB34fCLfbGv9Q6/aTlX4S8uC+wie/bVOhj/JTm1bIfiIGpclcnZ0PSkyGd5d0ZBKoWM6fhgE6LbaHIZe/ONQTGt+nzsDxfE1rvYjHll6/Daz7wtEkschPJ9IK6L9xx+dlfUAVyWKUg4WuU7og=,iv:8XS8a6msde2j0I+CEi0XAtnYsRTpeMOF/Zqr7vCxMA0=,tag:4C0Jyy8aqrQzZQXiLqFm0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
