apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ZmYXN6f2HUEfHmIGhjvhr6XnQB15YwYWJe6otnpDTNbpAEBm,iv:HWbyrkPGjcn1ptyKTU6nY1EeZIJAVSJkJ3k+8q9EDro=,tag:9v2+KEuKY495ZZf6+HY7Qg==,type:str]
    credentials.json: ENC[AES256_GCM,data:h+lk1f3SnCX3Mshwl6a9BmejdgLzwGvBHM2mZLAVAvrUTPe79eXPvG/isF496xKOcnnEiKsXr/RK+yiOMDb66wbk92UdGx+ox2/yyCicgZNfls8WmkkMUCuP5EXD0BAlB6ii7jUnPhgbn0IT8MhHmSEWM7eW8ioCDs3LeMrm7pb/IbPXJ3YOvMj7PYZvIxL3E0guaj/dbtzA44P0dKaJzMonoIruIRbDnBpB07K1sg==,iv:f37oqX6ozmrQzR/mozSv6/aFScQ653DH3457MCfk1MI=,tag:JhHflQazdbJ1CGLcNrtI/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eg2mmjn7jwd2qqs4nppsz3pehxrkatw4npx3php5eqxwcdc92a3qkpd3t6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTnZJcXRGM096U0xyS0E0
            VjZ5YnRnSURiQUd1bzZsUmtsZjNCQmRRSkdnClVvQjA0Q0wwQXU5MnQrSCt6bytz
            Wi9VZlpScnNwUFE4ZXhKeVpkTVJJUFUKLS0tIDROWjV2R1R3R2x4YkhFeUVNaTlx
            b1hMTkFsSmR1MDZRZkJmK2ZUKy9YTTAKnNex/mEw5OiXVyAikLk1mEmIUtKcKp0l
            A1t49BYP5W/LNc+MWp5exCHYEERf3LGrZeh53Arm/aTbKe920NFPaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T16:33:28Z"
    mac: ENC[AES256_GCM,data:1T/FHVkmCRBWOm/nUXnFHxKJNeTlMQYqavzDJrqUMwuJhRfFGSm3/0ag7D9k0booVkZE4FaJcSXRaAP6jr8zqcaHjtMLg5V08sGCZPc45PIVdJC3jK3RMdlGiDV8FPXlpMnPDsO/EpMz97asUqU3rulyR6axzSkXK9edfdbnLNw=,iv:BY4lt99kEAWRnFgrWh+fCT4PsUizMHY21jEAzWqx2/c=,tag:xck8QkSk8BDCso3A8ojC5w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
