---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: teslamate
  namespace: flux-system
spec:
  targetNamespace: home-automation
  path: ./kubernetes/apps/home-automation/teslamate/app
  prune: true
  dependsOn:
    - name: external-secrets-stores
    - name: mosquitto
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: false

