---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thanos
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos-objstore
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        objstore.yml: |-
          type: s3
          config:
            bucket: {{ .S3_BUCKET }}
            endpoint: {{ .S3_ENDPOINT }}
            access_key: {{ .S3_ACCESS_KEY }}
            secret_key: {{ .S3_SECRET_KEY }}
            insecure: true
  dataFrom:
    - extract:
        key: thanos
