---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        GF_DATABASE_NAME: &dbname grafana
        GF_DATABASE_HOST: postgres16-rw.database.svc.cluster.local:5432
        GF_DATABASE_USER: "{{ .GF_DATABASE_USER }}"
        GF_DATABASE_PASSWORD: "{{ .GF_DATABASE_PASSWORD }}"
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        GF_SECURITY_ADMIN_USER: "{{ .GRAFANA_ADMIN_USERNAME }}"
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GRAFANA_ADMIN_PASSWORD }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .GF_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .GF_DATABASE_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: cloudnative-pg
---
# # yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1beta1.json
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: grafana-admin
#   namespace: observability
# spec:
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: onepassword-connect
#   target:
#     name: grafana-admin-secret
#     creationPolicy: Owner
#     template:
#       engineVersion: v2
#       data:
#         admin-user: "{{ .GRAFANA_ADMIN_USERNAME }}"
#         admin-password: "{{ .GRAFANA_ADMIN_PASSWORD }}"
#   dataFrom:
#     - extract:
#         key: grafana


