apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:FcVqO7vRp2+10sZ6Twh4B32eO4R+/a57q5ewYqPP/H71JmBj7WEPXg==,iv:qDtKICTb5HNRTP8OQJOJPmGsaujqrwD1KO2/JhsHl/w=,tag:IBluSyE2p3ldrhwnJ/jhPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dfs2z6esr6rhm46pvh6l8xlualxsn756rkkt9432d5kk3k7s4pssmus4gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGczFvcHQ2cjJ1THMyRHFR
            OEVUWXducGVvNWVkNVFiTXB5aERsa28zWEJVClB5a3dJVEdkSUlLdFhlNURLL2tK
            RG5YVmd4RTkzVXRpRHR2RGQvSHNvYVkKLS0tIG40WDMvTU5XSmlLM09LSDZCbUc2
            VHBkaGhwaHp6aWlYSiszZUtPR2hKaU0K9Ppm5OjYKA1kzNUaADRa83Ad77CUBYhW
            R0NifByxUbRMYpgX9NFPBqK13bqJXl0L4927lMnm37FBt+aKrdEcwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T09:43:05Z"
    mac: ENC[AES256_GCM,data:EkM6bJ+zKP0uHgewhz9Z68Ys3qKkQLgGAhfeCwInczU/Q/410+2eOfULhg0v/KnK4JUNPAKuOBMg2Sj1ROAVeuIvppQuLcERYujUTNiwIZmZrlUqfRhLzmuaiGBxaR1RQq4pZDFigyZg9PbgKpLCaL+j4Yyh6FxhfnHW+NiID3o=,iv:04sf9487Cw+JmdVm/PYg+wq7ha/OVyZv0kud3dcVbTc=,tag:VBHwT0PMyjp21vujUCHboA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
