apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:uEMhdBNnqgVidg/pA79sP6FGugQvb/meXa9OPtQk5XB7pHy3El/mLA==,iv:+PQXrUaMBZRe26K0qyq4VjnxUq2137/w5L8GmXA/zmc=,tag:c9Tcala6euseg12WVI2ceQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eg2mmjn7jwd2qqs4nppsz3pehxrkatw4npx3php5eqxwcdc92a3qkpd3t6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWbFNoL2R2Vy9oL0pRaWRo
            YVVOUnI3ZTlYZ3BPcTFOUjZqcHJsZis3bmg0CkRhejZMajFUWjJua3o5b2VWdkZU
            YkVZMm1xZHJGb0lyMk56NzdKQjVkQTgKLS0tIEtkWnFJQU9jNWdEeDRYeTFqMmFn
            UDVWU3d6aUFRcGtnSXVrSU1kSE85UlEK78Sqz9P1cFWoGxWJTUPkG7YzBr2sJovk
            drnRRSFBDApSRX6Lz0bUZf7w3pw0EtOBbEt0ZwqfGBvA4IUGERZRmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:37:14Z"
    mac: ENC[AES256_GCM,data:RNIJ2g+Zrr9HPXA0Xg9bE9WgYxEOBi8J6/6mOviEWmjZd3OnmcTpM+hdvRKnCUM54e64M8TycypC5BEp3+RnBYhM/numYDfNgo2QnuTQhOIqPUHOR9YUoxCGAwQhaCScBEgRtKiDnzGpJiwtvoJv7YGz8gx9qQofoRJrtj8hWdU=,iv:J1XTqjf/PuqIAgNnf7C4p1Ie5TF0W2TwlQMMieJLygE=,tag:xVghqJ7ugIKF4wIP0Z1DZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
