apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:R3VcxWbO/8py0Tdvl3smNd1cfJXt1higC8mL3Lf9a4LvazP5i9TcCA==,iv:NTentV5HTn/VNK6W+iQGwlZ8DFZW1hB8ZAmbk42gYrA=,tag:0B/8ungaPZ7eFLPxHu2etQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dfs2z6esr6rhm46pvh6l8xlualxsn756rkkt9432d5kk3k7s4pssmus4gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ0thclVwZXN3TGQ1bmJZ
            Mk4yYlN3Y3hKclNBeEtwK3lWU0xnQ0IvbTA0CkcrRWlHcHhFcjk1d0t6czdHaWFp
            dG5lbmhmSXl3eEh1N0lIY09NM1J2SUkKLS0tIE5BblE5VXlWUm8rTEsrSTNqb1hO
            cnJnTS8wYWJLTVc4K3FVeks0MUplZjQKTqrSUFJOVVPAjisQvdE3P5pPTFpY1+XV
            3STsKxiyxySgmtP+ISfBHts28/Uj91pjCMPp/UtBEoWxewiC9tF6dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-20T06:09:03Z"
    mac: ENC[AES256_GCM,data:cHAAHFfsZ2ps9QBoBC/oSUKgWaL1yi4mcxAv9pqLAdph3OB4SV4V7nU3mZ4LYPxZLQ7DCT9qa+KMpUyYN2di8eItVHjrL/3tx5c81iyS9w0QW7o1N9b4mH3/PDqwGEe9tdxzflY9VRfe+ILy2Hzyi41nUOEWEQf+az9ipF0vsA0=,iv:v0pEZIM6wYoOWUasJAiAOr4V355WF/Fk324xKGheKiE=,tag:2An5AAjlpFwp1p4XfA58vw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
