apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:hrPU/XBUrjQQXxgpQyWYxBo9dduIU0+gH0V18ePBVz13yaFdBX6rew==,iv:0MseO3nkW6ajwZwPCmqeQpQw8JIn+2ymtAc59Hmycpk=,tag:qAOMzLaInFCfrtoqany0GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwpkc7nndlsql07awyjlgynhlmwnt0hjwncppqa7ctf83acwwpzsuxt97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2QVY4WlhJbmkvMy9lcGMz
            ekJWTWlLZGJhK2ZqQWFFelBiZTRoU2xmRnhrCm40U09WR1N1U09IWVNIOUxGSWkv
            ZlhibWdhM205ODJrRTVQT2dBZkZkcW8KLS0tIGcvSlhGV054UnNqSUcwSFRteHpK
            eHA3cEd2TG9OZG1EK0hmZDB2NDNpY2sK16eovjkp4qdLxGUXqAk9v/7z5uAYp0Po
            Cv50S8swN2Nrc80DWa3FPrF8el28zU70VwOV9/Vzys4Y6GW51MYcyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:12:01Z"
    mac: ENC[AES256_GCM,data:uwnlU3wlGrB+cwfOHOYwEJErbUefjBMspjbnHmkhBX8GUeDqH+iDGyKo/JseFxZ2q5OGCfDZ8s3954FFQjiZSIGoXgeIfpVvdi2ig89vFKwBgJsxbL/0NC0ruF9u7KEVtr4W8fJ/TVOxtW54xU0/v6okfdcof62sGt/COpJHuxw=,iv:d7hNJvHk8yfwNV6QAhTyRNMYfZWjowdSXC8/xrMjS3E=,tag:VIvgVPZmdLW0l3teHEvyeA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
