apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:EsKpA45Ca6d5mn9ShIfKgpe1sGwfNR2QfZcfLanqBRqKQyBO4kYDtw==,iv:iPeCbp+tmS1P0oHRUZqMQLn01Q/GcrfcQFcvSJpGIp0=,tag:jWZx0CVFe7pyXnMY2PSKow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eg2mmjn7jwd2qqs4nppsz3pehxrkatw4npx3php5eqxwcdc92a3qkpd3t6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZjRscWQxTThXRC9mSzVM
            SzliT0k3UnA4K0JBSm9lK1VUWmdyMWdoVkJ3CmxXenJEWXFWNHNpbXNQWFVDaFZh
            K21HbCt0cWtVQTNlbUo5aWJkWFBNVE0KLS0tIGhra3VYdk03UVgzV3NNaEE4c2Ft
            N0V3d3lmNWY3Zjh2WW9YRkEyZWozNW8Kn+HhafpnQlfuUNWQHyO8yke2UAAknIgk
            QLHjaNdCenbClLFzKErv1T6zA7MbLlFtgboDY25NOgWmxFWx8VO1ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:53:55Z"
    mac: ENC[AES256_GCM,data:EbDvZmApTcLjfFzkasi4983vbsoFRmDRfjaxsIrxLgCUy1JApO8lp9TcxO8ErbawQK+1s6MiNfQ3kei3BxvVQiPFdb0YL6QH/92CZ4+m4hklDaUU1bPaB/9thoR4jJ8c8N6SK5u3O8nnAemIK7cpRA7bLmKSL6TA8e+Or6ZXbF4=,iv:xhVY55HXv16PWLrD4Za1KsvE/rJRSZxukaQhnCB7QZ0=,tag:9g9TvoQahyGYC9JXKVviCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
