---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: node-red
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: &app node-red
  path: ./kubernetes/apps/home-automation/node-red/app
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  postBuild:
    substitute:
      APP: *app
      APP_UID: "1000"
      APP_GID: "1000"
  prune: true
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
