apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:h7oef2MV3Uik5UKqoUM=,iv:Cwihp46VYSia8hbC37jCf05K2JibfzL/9QVoiaykyFw=,tag:vHwxJJg9wChSb43fV1DFOg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:3t1jW3gxRU/dMI1gxbc6OARIWg==,iv:UANUtmsH1eAcdqNwsN259oo35sm/MNbOv2XW7m84IEM=,tag:YaRhW/TPl4GMlUwcf577Lw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:9c7hmIeeB+lcRiOLSm1+ej6bEqpNXNDixCPyBbCqReJ3InMX,iv:WorPAfRaAaMnWEnp6E++JJSWZ3WXOiTTBPnPwabs5VA=,tag:2qtDdMf42GRz5mVtkypLug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eg2mmjn7jwd2qqs4nppsz3pehxrkatw4npx3php5eqxwcdc92a3qkpd3t6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTNGT01oU2hLQ2xZLzFT
            dm15UDRDaFhGVEx2bll5N29VVzl4d2JyWERRCnNsMEcvamNSNG01S0RlaXBzYzhL
            NG5RdURja0lEVlpjUDFmckcySlFXZ3MKLS0tIHdoU2lRb3dZaUVTdmJvRlNmNGJI
            cllJcjBZZ2l4MDc1VUVSb2ovcm51NXMKwCI5JRGVBol5Uo0wDuIphnzcO1QiFuuT
            kV0o7r0Nwk/8lKf9AKG6lkr96OGGvd15rJsmQoffEaW1PsEU1WpC0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:53:55Z"
    mac: ENC[AES256_GCM,data:NUBKC594ru5su4EB91vG+d+Gg3BuSb8ORwv/UtGINlLuw+DuLfu29tAYFsAwQaYdLvA3lHCLDVVIKyB7C14oHs5dv8CE41Qk1T7vNt5QbePTJRBzojjksrhvuMqZb5c4k7XNdDU2NudWdL7KSnbf+HOLPyj4qN1hFMm63YmZNQ0=,iv:AfmhuP5l6a/ZkTehVauSAUoYo+YiofHkquESgLdJKjI=,tag:TXJYLRn8F2+Y2+u/Ui6xDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
