apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:qKqgvSTNmE+oi/ZyP9E=,iv:fa63VKGg9eWPKaBKKQLk4z/a0yigivTQlW731kM3TjQ=,tag:Wbky/qf8blleuR5R00oKtg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:HH+iAFcE16+lRhxTFYf19howuQ==,iv:vKTm7u71wLuj3xyvXAQ0vkGj3soNAIL0SkBWobvkbp4=,tag:UnXOM4jEOkg/sNDR0iqkEQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:fs5VdhmbRtv26dPigc3OHW5ljNrR7klAGIRWk44oDHlooiVL,iv:39SU1Ya0fVr9+3EO3yc4ZjWBtrhprX2tmRP4ZzQS4Bo=,tag:7wpzZDE7THY3mgq+4rnptw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eg2mmjn7jwd2qqs4nppsz3pehxrkatw4npx3php5eqxwcdc92a3qkpd3t6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRmIyaVgyYUI4bitFL3FG
            elhCanpwTG10ZWlqUXlIOEd6cFp2TFhnczN3Ci9TeUZLcWZ6SUg3c1pvbUZ3amRa
            M1grWmY4cjJ5d1JCbzUrMUhvZThScmsKLS0tIDFEaWY5OVp1N20vMzBLTjdPazdE
            YWdYOFpWaWtCQlJxZkYzSGlxZUJHV2MKr7o4BQOW3oPWq3/fIjebuzs57iFgwA7+
            48d6T7Wjg2ONM8ng93/MsyVHsGwrDWok+XiTnOaK+vB3kJX84ofqZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T12:09:24Z"
    mac: ENC[AES256_GCM,data:KRYz8XMruI3e4ga0YfdjpWkg8ex2DVUwaFBLTZ5g0NypXQuqgSlHdD07RvehRocZohAX614iO4d882suM9ostm54KjNrB5UnorE436bVYWptBtZBpkFRGnr+FNip2WUV6E/sAxyWyw2yAOINxBXT4vph44/1Jt0cU6wwAW0lqZQ=,iv:KyEzKviySfS3caT06d88X6ZMZnPU1rDyvHjyyPdsofA=,tag:2NdE2HhLGtWyr3508YAkww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
