apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:OcuV6aghbp/7+icHMaQ=,iv:tuh7LlwAQQ53TP9vWevmd3tP68iZle0xCDPOqNjnbPY=,tag:8Uo5+kOy6iKWJxd4DJohyw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Xw7eUNcBx1v43VJxCc9Pa8ubVg==,iv:LXGDLLfQn7yco8O7Vc+U/Jrkxy10UYyi+Uwx7ZEEQ8s=,tag:f2DYvNkHvHdrVwXlqfoQJg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:xL7sat5veXODzU/XdoHVCQOGYDEWyZt25Mg0dGwjv/tcCyz2,iv:3zCiTTs8mTFp9WUVr6MZYJP/BIqXz2/6/TK5anUzcWM=,tag:8L6CERkwnXM5jsOn/R8dKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwpkc7nndlsql07awyjlgynhlmwnt0hjwncppqa7ctf83acwwpzsuxt97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd0NVY0RGWktVcU1KZ3pP
            QVNrdUFwak5ZR295TUduY29UUC9Fb1NQbHdZClhZV1NRam5paDNIZWtVZEY3RHFG
            bDJ3M2ZWRzdsQmhhYmFuWFIvMWJiUzgKLS0tIG5zMzVPMFVZcEMveG10b1p3b1Qw
            SzJSUys0ZGI2eFUzRi9NOGhVYWRiSTAKOnQLtUa+im/pYpqboD4HvcG/LTk/nbGk
            ZPMLFU8AQIaUrExXFLAyotslDQpAbUPtrInApCcGDqHU0dZVce39Ig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:12:01Z"
    mac: ENC[AES256_GCM,data:6N3eQLScm23m8NfLkUch/8mPRqQ0s3Yt+JzNgJwgveddF3cGU1SnajsFoxe/3No4bU4PWLRptR+RogXmbXboGpmIkMLz+s/1CX9vAp+3f5WQt+ZQHlMF3qG5RTsx0jbm8eBLbcjGzQlYxjG9qNn/Q3vCjZoRb2UGGoWIUC0NJLQ=,iv:WU9O7fccGMcD2oUc4Ussak34biq6qh6F34xNtLBYRhM=,tag:nynrGgUUeCkYpIcwWNQC+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
