---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      defaultFsType: ext4
      reclaimPolicy: Delete
    replicaCount: 2
    ingress:
      enabled: true
      ingressClassName: internal
      host: "longhorn.${SECRET_DOMAIN}"
      tls: true
      secureBackends: true
      tlsSecret: longhorn-tls
      path: /
    defaultSettings:
      backupstorePollInterval: 300
      backupTarget: "nfs://172.16.2.246:/volume1/clusterbackup"
      defaultDataLocality: best-effort
      defaultReplicaCount: 3
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      storageMinimalAvailablePercentage: 5
      storageOverProvisioningPercentage: 110
      defaultDataPath: "/var/mnt/sata/"
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1024Mi
