---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 30m
  chart:
    spec:
      chart: promtail
      version: 6.16.6
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: promtail
    config:
      clients:
        - url: http://loki-headless.observability.svc.cluster.local:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true
    scrape_configs:
        - job_name: syslog-tcp
          syslog:
            listen_address: 0.0.0.0:1514
            listen_protocol: tcp
            idle_timeout: 60s
            label_structured_data: true
            labels:
              job: syslog
          relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: 'host'
        - job_name: syslog-udp
          syslog:
            listen_address: 0.0.0.0:514
            listen_protocol: udp
            idle_timeout: 60s
            label_structured_data: true
            labels:
              job: syslog
          relabel_configs:
            - source_labels: ['__syslog_message_hostname']
              target_label: 'host'

