apiVersion: v1
kind: Service
metadata:
  name: promtail-syslog
  namespace: observability
annotations:
    external-dns.alpha.kubernetes.io/hostname: syslog.${SECRET_DOMAIN}
    lbipam.cilium.io/ips: 172.16.2.235
spec:
  type: LoadBalancer
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 514
      protocol: UDP
    - name: syslog-tcp
      port: 514
      targetPort: 514
      protocol: TCP
  selector:
    app: promtail
