apiVersion: v1
kind: Service
metadata:
  name: promtail-syslog
  namespace: logging
spec:
  type: LoadBalancer
  ports:
    - name: syslog
      port: 514
      targetPort: 514
      protocol: UDP
  selector:
    app: promtail
