apiVersion: v1
kind: Service
metadata:
  name: promtail-syslog
  namespace: logging
spec:
  type: LoadBalancer
  ports:
    - name: syslog-udp
      port: 514
      targetPort: 514
      protocol: UDP
    - name: syslog-tcp
      port: 514
      targetPort: 514
      protocol: TCP
  selector:
    app: promtail
