---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.bluejungle.net
      vaults:
        home-infra: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-secret
            key: token
            namespace: security
