apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:QDecM6g6H4xBmzLZsGKMeRQToxJo2bksQ1A7M7TDSyg=,iv:3Yq2UVbUp+ycSk0f5mxTIXagowwhVuKeT0wGks/NkkU=,tag:KKu+OHiQK+ltDyyDfM3Z1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x65r69cnnqajnd9z5e5p0smvx5vf7q0m0k08ntp738y2atyltfwqent5sm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVUJ5Y1p6UnhBSWNUT2FR
            a28yUUs2RVZnZFVJYUo4VUo4QlAxdTZsNUNnClRBQkFYTHh2MDVObEFiN2pLbWFO
            YVZJb1JKRXI1ZnFtaDVnUHhhb2w4b1kKLS0tIG5ETTFiRnk0TFdDZXVaVGRRZUQy
            VWRXMTZBdDZJZlkwUjBqeWcwV0g3Wm8KjzDNBhPQVZKR5Oc3oMFQWbtCsAVVplwx
            DB2CdlFJOoEpGi/r9igVOUwszCP5TERktV+aG9d2hkpOEhIjnkNxEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:24:10Z"
    mac: ENC[AES256_GCM,data:hlfArnnJyWOfe9ePHNhvemB30d/sirZW59Ev1VNPR4bbHc1f6W1o5R/ChPkwGHNVQzGYf+FA5+Yq7sKnjDGSSWg0NwoZrPhs6oSPwsBVkXWz4Wz8VtZRY9klkik27ndmvQn4pcqPfJdF8MuaBTLv7B3UGAsxtoDukaiwAx9Qvnc=,iv:TdTFcec2+ZYW7GILcenhnmv32Y0pYgt6pOa8TiM2Uec=,tag:FJ1xjyQ9tZFNyDG6DRGZng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
