apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:aulDy7ua248muAy/fjTzS5yFARjU3I8Emd7T4B0gu5Q=,iv:mz4ciOW3YVkLnqPv0Z+mKcDIINt/0iFDI7RRaowz6MM=,tag:oPfhemRsWqhHX32Bi+n+wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eg2mmjn7jwd2qqs4nppsz3pehxrkatw4npx3php5eqxwcdc92a3qkpd3t6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQVd3Vkt5L0pZRHdOR0NL
            ejFvT0toMzJSdTk1WnY3RGtDN3NnbkRBK3pnCmNVOWhYUVc2eWxVcWxzVm5RZG10
            MCtiQmgvNlpYL3JCcHJJbHhLVW5Nb0kKLS0tIHczaHhFRUhZQWU0bXY2TTBnaTRC
            TEVpcXNHQWdmZk5DVTB1bWJPQWw3WlUKue35XJ7+sVhta8rFJ5aYjWHhQhkt58q9
            YU9V+VJjgQ1WM2w+1Bju8eXaCWjq7h63q9mgH26ZRyo7Sxk/x3/aUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T12:09:24Z"
    mac: ENC[AES256_GCM,data:JkVcJVcljL7o+gFFGzc1Imn7mpghJRcsD3ou3Ko0Wq/qVVhoIKrtz5ekYnQbyB5+KGQ0kdiCqEYgdhXtnQ07IQvNMyUObv0mQ4D/9utyrAwyUOOHJeY07fH1yPkB/iP9Xk/d9FH35suIjjeqbL5OlR7j5zEyRwESJKIee/x5o6I=,iv:1Dr4AASaZUf3E8U0M3Q5Bf3N9Mg0pm5XzQZNCiM3P8A=,tag:PElg7m5ZusF680eu5GWnTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
