apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:PZNQouwGKJrJMNvFKYuWbH+rBzOt7kNtiq5n1HIuIyc=,iv:RfQa93rL5bTx0W94eD0yNjvtdbF2VUZGqmkfajZfIoM=,tag:MW498ZARsz66EAKopDvMxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwpkc7nndlsql07awyjlgynhlmwnt0hjwncppqa7ctf83acwwpzsuxt97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3N2pCaEtQSTlkY0ZyK3Z1
            THc5cVcrOGtyaFlZdEpObzFobnZWUVAyK1c0CmVLaWxML3NvUVczQ200SSthQ1lk
            bkF3V1R3UGQ4KzAvaW9KZlYvK2pWRW8KLS0tIGJIQm1QdmNHM0tVS0VkcmRVeXhm
            UE5UM25mMXVJaGpwRkdoczZrTmJkQkUKvacHrqOF/wVGyrydXv8wYf7LCJeaZx+I
            /P+c59B+DO1BI3CQq9I9iTdbJJOeT3qDrxvyeoJDHveAyyWe4BFvEA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:12:01Z"
    mac: ENC[AES256_GCM,data:sxuVzvoH91vSSTliMNTotVPqxRtvwybTm7hK2HpTk+Oj6JA8uH+P6lhCbF4KpwcAGjxEUrfamttT6X2A5Hb6FpyAoOBdwgS6Tr3encMujH3F9S7Dmj5EnqY1G7ZJpwpDPDN02T0TBRucTWRWrLZmOJX+5ak8qkM33oGqM8ZC+9M=,iv:CphpjGYkNrLNqXbAaMTlEei1pO2le+LyfelaPkSiZ5Y=,tag:HJcBeNVQntWpXT6i5jksQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
