---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: teslamate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Teslamate
        MQTT_USERNAME: "{{ .MOSQUITTO_MQTT_USERNAME }}"
        MQTT_PASSWORD: "{{ .MOSQUITTO_MQTT_PASSWORD }}"
        ENCRYPTION_KEY: "{{ .TESLAMATE_ENCRYPTION_KEY }}"
        DATABASE_NAME: teslamate
        DATABASE_HOST: postgres16-rw.database.svc.cluster.local
        DATABASE_PASS: "{{ .TESLAMATE_STORAGE_POSTGRES_PASSWORD }}"
        DATABASE_USER: "{{ .TESLAMATE_STORAGE_POSTGRES_USERNAME }}"
        INIT_POSTGRES_DBNAME: teslamate
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .TESLAMATE_STORAGE_POSTGRES_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .TESLAMATE_STORAGE_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Teslamate Agile
        HomeAssistant__AccessToken: "{{ .HASS_TOKEN }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: mosquitto
    - extract:
        key: teslamate

