---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: influxdb-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: admin-password
      remoteRef:
        key: influxdb
        property: admin_password
    - secretKey: admin-token
      remoteRef:
        key: influxdb
        property: admin_token
