---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zigbee2mqtt
  namespace: flux-system
spec:
  targetNamespace: home-automation
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: mosquitto
    - name: external-secrets-stores
    - name: longhorn
    - name: node-feature-discovery-rules
  path: ./kubernetes/apps/home-automation/zigbee2mqtt/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
