apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:UMhmDA2fetcvNEn8SdmrV2bFrsFZtANJCfHWqcxbcsjTTJlt5ELnYA==,iv:fq5AJHq1zkr9lSIlgFpEyEqZSAT5VwFo58ncnbWRz00=,tag:F213I1ACBYYgMHoGN6CnKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dfs2z6esr6rhm46pvh6l8xlualxsn756rkkt9432d5kk3k7s4pssmus4gk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWlRTMGZRSmg0VFpMZWNp
            UTBrOXFUZDFjRmF1UjJQV09VNkdSQ2t1MW5jCkxUa1ZKTWczdGFyTVpuNHNOMmhp
            TExWUG9RQnJCNWQ4cUYzRDVvVjljYnMKLS0tIG9lMmt2elZGUklMbmxGS1VNOTFQ
            bDJjMUNnNDRveHhtUDlWc2R4VE8yUkEKp5EIKm71HjtzIamT2nLSlLrvQ5Cfz3DC
            lvTgwUGsi6Q8+XcqNRxIAam7gaCT1YxiLup8e3Amv958t9AqxrKIjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-19T22:11:09Z"
    mac: ENC[AES256_GCM,data:hwLgitK889mFZD+L0mxdENcjXmf3R0PjnATKHlG9xI6yvb+oM49oh4BjHY7dlKEwOa1Of9r7jDx1vXTbDF/1T2ob9WNHqcJTIv+8nkQTw44MBXU4BcSo8DJMLHGSAcI6kS0mVevEmT1RwSDXUSyhG4fGzfT/a5wThCxNXUfcwFY=,iv:XnycfCm1QfuTqqTFG54TVny6fhLZj8L+SsxjPsInTcQ=,tag:s2z6LVrX9rT4orVEns2Zeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
