apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:pHVgvB07zj5QJAUoyuKAzlE34oBOa9oGeHlC7mPGC1tuVUT9hd8Wrg==,iv:ZzE+x9uHuJPi7gmBLIRsYwKQr8Lp3UsCHfo9ho9ByC8=,tag:3g0WiJrUo3pjroKogvGZUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eg2mmjn7jwd2qqs4nppsz3pehxrkatw4npx3php5eqxwcdc92a3qkpd3t6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVWhncU5nRjFIbHhtYXFu
            aDJZZWwwT3lLVURLTDJkeExqSVVmVVJQajNZClJEcFYwdC9YZDNpcGJ1SkpmUXZo
            eGg0WlNrRzExdkZoNEQ4cjRGa1V5M0UKLS0tIHl4eWVROXRoMlhUakxGUXhpNFFU
            Y1VNQTl6SEc0K0lzQ3lmK3F5cFMxalkKO10YdXLIhvDvLbn5NrisqGjdUiHbbOSz
            nGaGWKfuHAmkzqhnRmsTudJfCIUXFDzPOOmJaqpP2xO2ylHeg/cawQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:37:14Z"
    mac: ENC[AES256_GCM,data:wfo5ERovhxZ51Pkn+yFvwYjVsrl0qAJc1GR5/eFLfcx67KggE/5e+oYvVrRfMbNNe3c8yGgyDsJImi1VI3cwYNAE2RtkBpN7aBiImWjhhTi8MRbIDx06PUSuwO7ogrnwsBqrYjtfOwovpD21YU/a4ulY+yRZRyLIpjEiKl8XKv4=,iv:fgjoHSrlca6XjIy1jxY5VjHGRFQKKqGCkIpgKEuErQY=,tag:yHsXTsToLm0fwDTYb54yAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
