apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Da8G8kRnA8zE6YW6iY0IDUzBhYO3QtXU4iJIzsQEbLSMDXV9ue1A4Q==,iv:huzmtGoABklO23fdkdkBQhBIZ9LeRRrJKVw8bjn8j7E=,tag:1bIJ7Ufr4VxVDmXr7kMQwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwpkc7nndlsql07awyjlgynhlmwnt0hjwncppqa7ctf83acwwpzsuxt97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RkdtWGl6aU9OUlFkaEpM
            aDZEQWxIU1paV0RvcGVXSUp1bW0zdzUwdGowCmhTLzZUbDZnTmptcytZQVdhalhS
            VFJuNEh4clV1ZDBTTFlld0k3Y1pxTFEKLS0tIE0zbTBYb2dqakNrR2ZBNmM2SjRV
            RTVTUHBPcmM1ZGMwQy9KelRHa0prcEkK3fGCBwU/FiUaroS/4vl2w/wBb6WPvpOC
            Lkw4D0TeEbgfqfIA0IHEi+b7Yd3wQJTanqNbQq/FP3CEwNn29qODgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:12:01Z"
    mac: ENC[AES256_GCM,data:WtAGB8N0OY182IFBwUN8tIs0yyjmWBnP0BMTDwQJyIuwYaWphWFU4mOmQ6iyomCnO5BW6a0tGAVqFLKaY14t0Ck/1zgQbHHI80dmYmt4M4DWJ42E8nkSpblyNVtZAQ/zTSwmapBij+1qdYMJNWgzJyNTkxV0Uc63i8ODcSyfvCY=,iv:XYI0SO1jc95kuwwPq7i9Y4hEYZaf5oKLWYcqY9LP8IE=,tag:ZqNRLbTLg+Py0kNHcfKZMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
