apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:fVVBbOrAtsWlXxKrcUXuIUEFjwBV+ivQ1IETclk3LlfMXLbX6lxT6A==,iv:S+Zrb4Pgn3xgefatlLOZMElNQ2G6wnbnYWV4AZTdwGs=,tag:UebI8oH09xZ5wYzw/BVdcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qwpkc7nndlsql07awyjlgynhlmwnt0hjwncppqa7ctf83acwwpzsuxt97z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYVhwNFlLWThJdTFNNFZV
            UmU2VnExdE96SEtRREdHaUZ5cWozT2NiR0VzCkp1ek40dnBLcjhSTFFrb1lKbUdH
            SDE0dmhMZVFCRDZaMEtlWGJjQmt2ejgKLS0tIG1Va1gwSGR5dThEVVVLK3JJek5v
            eUp0dTVlV05oVG9QTmRwQ1JNNFkrb3MKJ9BrBONGtnzDQ4fIihGv8sF3sCLGsDv3
            7YcdbN1VCfqkZe3L7NnFECo6pylgoeqWHSXvWuCuR0fKi+ThQ7b1cQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-08T08:16:10Z"
    mac: ENC[AES256_GCM,data:BVlTt/tNn0LyWiT2huQNYc/ZlyfB4ik67OhvbBgVx7squIpxEUPZFc30UJavEoNSdEtDhXYFrhFuWRmij/nmKFvUm9qq8Bbde5mdj+Y2nSngFIXEl7osLV5s8jVQaJZGfn3akvPXWz+58tZJ99ikzeP71WZYniu8z+LUrV4andM=,iv:2aFL2fCHg0bAQ9iqzw5VHCCb7hfJejYyDHnS0Z/cHRE=,tag:5CXOBhzmQ9v+TOUvxpYERA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
